apiVersion: v1
kind: Namespace
metadata:
  name: scm
---
apiVersion: v1
kind: Service
metadata:
  name: git-server
  namespace: scm
spec:
  selector:
    app: git-server
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: git
    port: 9418
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-server
  namespace: scm
spec:
  selector:
    matchLabels:
      app: git-server
  template:
    metadata:
      labels:
        app: git-server
    spec:
      containers:
      - name: git-server
        image: alpine/git:v2.26.2
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add -u git-daemon
          git daemon --reuseaddr --base-path=/git --enable=receive-pack --export-all
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: git
          containerPort: 9418
