apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emojivoto
bases:
- github.com/BuoyantIO/emojivoto.git//kustomize/deployment
patchesJson6902:
- target:
    group: apps
    kind: Deployment
    name: emoji
    namespace: emojivoto
    version: v1
  path: ./auto-inject.yaml
- target:
    group: apps
    kind: Deployment
    name: voting
    namespace: emojivoto
    version: v1
  path: ./auto-inject.yaml
- target:
    group: apps
    kind: Deployment
    name: vote-bot
    namespace: emojivoto
    version: v1
  path: ./auto-inject.yaml
- target:
    group: apps
    kind: Deployment
    name: web
    namespace: emojivoto
    version: v1
  path: ./auto-inject.yaml
